### ISSUE TITLE
问题？

### ISSUE THREAD

**Issue by JankingHuang** [IKeepMoving/xuexiqiangguo#5]
大致看来你写的python脚本。我是玩android开发的，Adb我了解些，python不是很了解。我就想问一下，你是通过python脚本模拟用户点击操作吗？

**Comment by IKeepMoving** [comment]
是的

**Comment by JankingHuang** [comment]
@IKeepMoving 我今天我试了一下，除了安装两个app。没有其他反应了呀！。然后脚本运行就出现了异常。
